// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfqnfmkfbafokoflmrdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmcW5mbWtmYmFmb2tvZmxtcmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDkzNTcsImV4cCI6MjA2ODIyNTM1N30.bj-bv7aJ_eovDWUvKxkqjICULDHnEizUndCOrnIfPOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});